# Generated by Django 6.0.4 on 2026-04-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvadesign',
            name='status',
            field=models.CharField(blank=True, default='synced', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='canvadesign',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
