# Generated by Django 6.0.4 on 2026-04-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_canvadesign_status_alter_canvadesign_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvadesign',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
