# Generated by Django 6.0.4 on 2026-04-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_canvadesign_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvadesign',
            name='preview_ready',
            field=models.BooleanField(default=False),
        ),
    ]
