# Generated by Django 6.0.4 on 2026-04-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_canvadesign_preview_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvadesign',
            name='binary_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canvadesign',
            name='binary_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='canvadesign',
            name='binary_file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canvadesign',
            name='binary_file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
