# Generated by Django 6.0.4 on 2026-05-02 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_canvadesign_binary_file_canvadesign_binary_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok')], max_length=50, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('connected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('canva', 'Canva')], max_length=50)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('presentation', 'Presentation'), ('document', 'Document')], max_length=50)),
                ('content_file', models.BinaryField(blank=True, null=True)),
                ('content_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content_file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('post_url', models.URLField(blank=True, null=True)),
                ('canva_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.canvadesign')),
            ],
        ),
    ]
