# Generated by Django 6.0.4 on 2026-05-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_socialmediaconnection_postedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvadesign',
            name='category',
            field=models.CharField(blank=True, default='image', max_length=50, null=True),
        ),
    ]
